/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


//ViewJPanel界面的功能：①显示（表格+文本框）所有录入过的体征数据。②提供View和Delete按钮。
//逻辑：从history里取出数据→填进表格→用户选择某一行→查看/删除。
/**
 *
 * @author Eve Dou
 */
//声明一个类，名字叫ViewJPanel。
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    //声明ViewJPanel这个类下的成员变量history，变量的类型是VitalSignHistory。
    VitalSignHistory history;
    //调用ViewJPanel的构造方法，里面的参数是vsh，参数类型是VitalSignHistory→说明这个构造方法必须接收一个VitalSignHistory类型的对象。
    //把接收到的参数vsh赋值给ViewJPanel类下的成员变量history。
    //populateTable();作用是刷新并填充表格，把history里存的数据展示出来。没有这句，表格是空的。
    public ViewJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
        populateTable();
    }
    
    //tblVital是我界面里的表格控件（JTabel）。
    //表格控件（JTable）里真正存数据的地方叫表格模型(TableModel)。.getModel();就是把这个表格的数据模型取出来。
    //tblVital.getModel()返回的类型是TableModel（一个接口，比较泛的表格模型）。
    //(DefaultTableModel)是类型强制转换，把它“转型”，这样才能用 DefaultTableModel的方法。
    //DefaultTableModel model = ...即定义一个变量model，它的类型是DefaultTableModel。
    //这样就可以用model来操作表格里的数据（增加一行、清空表格...）
    //综上：把表格的数据管理器取出来，装到一个变量model里。
       private void populateTable() {
           DefaultTableModel model = (DefaultTableModel)tblVital.getModel();
           //
           model.setRowCount(0);
           
           for(VitalSign vs: history.getHistory()){
               Object[] row = new Object[5];
               row [0] = vs;
               row [1] = vs.getTemperature();
               row [2] = vs.getBloodPressure();
               row [3] = vs.getPulse();
               row [4] = vs.isIsConscious();
               
               model.addRow(row);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVital = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConscious = new javax.swing.JLabel();
        fieldDate = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        fieldBp = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Temperature", "Blood Pressure", "Pulse", "Consicous Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVital);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 160));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setText("View Vital Sign History");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        lblBP.setText("Blood Pressure");
        add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        lblConscious.setText("Conscious State");
        add(lblConscious, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 80, -1));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 80, -1));
        add(fieldBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 80, -1));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 80, -1));
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 70, 20));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVital.getSelectedRow();
        if (selectedRow<0){
        JOptionPane.showMessageDialog(this,"Please select a row to view","Warning",JOptionPane.WARNING_MESSAGE);
            
        }
        DefaultTableModel model = (DefaultTableModel)tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow,0);
        
        if (selectedVital != null){
            fieldDate.setText(selectedVital.getDate());
            fieldTemperature.setText(String.valueOf(selectedVital.getTemperature()));
            fieldBp.setText(String.valueOf(selectedVital.getBloodPressure()));
            fieldPulse.setText(String.valueOf(selectedVital.getPulse()));
            
            if(selectedVital.isIsConscious());
            lblStatus.setText("Yes");
        }else   {
            lblStatus.setText("No");
            
            
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblVital.getSelectedRow();
        if(selectedRow < 0){
        JOptionPane.showMessageDialog(this,"Please select a row to delete","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        DefaultTableModel model = (DefaultTableModel)tblVital.getModel();
        VitalSign selectedVital = (VitalSign)model.getValueAt(selectedRow,0);
        
        history.deleteVitalSign(selectedVital);
         JOptionPane.showMessageDialog(this,"Vital Sign deleted","Success",JOptionPane.INFORMATION_MESSAGE);
         
         populateTable();
         fieldDate.setText("");
         fieldTemperature.setText("");
         fieldBp.setText("");
         fieldPulse.setText("");
         lblStatus.setText("");
         
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fieldBp;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblConscious;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblVital;
    // End of variables declaration//GEN-END:variables

 
}
