/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.user;

import Model.Supplier;
import Model.SupplierDirectory;
import UI.administrator.AdminWorkAreaJPanel;
import UI.supplier.SupplierWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Eve Dou
 */
public class LoginScreen extends javax.swing.JPanel {
    //成员变量区，存储这个界面需要用到的共享资源。
    JPanel mainWorkArea;
    SupplierDirectory supplierDirectory;
    Supplier selectedSupplier = null;
    // ↑ 保存用户当前选择的供应商，一开始是null表示还没选。
    
    private javax.swing.JComboBox<Supplier> cbxSelectSupplier;
    
    /**
     * Creates new form LoginScreenJPanel
     */
    
    // ↓ 构造方法区，接收资源、初始化数据、填充数据。
    public LoginScreen(JPanel mainWorkArea,SupplierDirectory supplierDirectory){
        initComponents();//生成界面组件
        this.mainWorkArea = mainWorkArea;//保存外部传进来的引用
        this.supplierDirectory = supplierDirectory;
        
        populateRoleCombo();//初始化页面上的下拉框数据
        populateSupplierCombo();
        updateSupplierVisibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChooseRole = new javax.swing.JLabel();
        lblSelectSupplier = new javax.swing.JLabel();
        cbxChooseRole = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        cmbSelectSupplier = new javax.swing.JComboBox<>();

        lblChooseRole.setText("Choose Role:");

        lblSelectSupplier.setText("Select Supplier:");

        cbxChooseRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxChooseRoleActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        cmbSelectSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSelectSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChooseRole, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxChooseRole, 0, 149, Short.MAX_VALUE)
                            .addComponent(cmbSelectSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseRole)
                    .addComponent(cbxChooseRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectSupplier)
                    .addComponent(cmbSelectSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        /*由于先前cbxChooseRole.add(...Panel)，所以getSelectedItem()拿到的是一个JPanel对象。
          （AdminWorkAreaJPanel 或 SupplierWorkAreaJPanel）*/
       JPanel selectedPanel = (JPanel)cbxChooseRole.getSelectedItem();
       
       //检查用户选择的对象是不是Supplier，如果是，就进入这个if块。
       if(selectedPanel.getClass() == SupplierWorkAreaJPanel.class){
           if (selectedSupplier == null){ //检查用户是否从下拉框中选了一个supplier
               JOptionPane.showMessageDialog(this,"Please select a supplier to login");
               return;//如果没选，提前结束方法。
           }else{ //如果用户已经选择了一个具体的supplier，就创建一个真正属于该supplier的工作区面板。
               selectedPanel = new SupplierWorkAreaJPanel(mainWorkArea,selectedSupplier);
           }
       }
       /*把选中的面板添加到主工作区，给这个panel起名“WorkAreaPanel”
         拿到CardLayout控制器
         切混到新面板*/
       mainWorkArea.add("WorkAreaJPanel",selectedPanel);
       CardLayout layout = (CardLayout) mainWorkArea.getLayout();
       layout.next(mainWorkArea);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void cmbSelectSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectSupplierActionPerformed
        // TODO add your handling code here:
        if (cmbSelectSupplier.getSelectedItem() == null){//如果此时用户什么都没选（为空）
            return;//表示方法直接结束，后面的代码不执行。
        }
        selectedSupplier = (Supplier)cmbSelectSupplier.getSelectedItem();//保存用户所选择的供应商对象。
    }//GEN-LAST:event_cmbSelectSupplierActionPerformed

    private void cbxChooseRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxChooseRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxChooseRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbxChooseRole;
    private javax.swing.JComboBox<String> cmbSelectSupplier;
    private javax.swing.JLabel lblChooseRole;
    private javax.swing.JLabel lblSelectSupplier;
    // End of variables declaration//GEN-END:variables

    private void populateRoleCombo() {
        cbxChooseRole.removeAllItems();//先清空所有旧的选项
        
        /*在登录页面初始化时，就new了两个完整的工作区界面。
          此时这两个面板还没有被加入到主界面mainWorkArea的CardLayout中，只是内存里生成了对象。*/
        AdminWorkAreaJPanel adminPanel = new AdminWorkAreaJPanel(mainWorkArea,supplierDirectory);
        SupplierWorkAreaJPanel supplierPanel = new SupplierWorkAreaJPanel(mainWorkArea,selectedSupplier);
        
        /*把面板对象直接add到JComboBox。
          需要在AdminWorkAreaJPanel里重写：@Override...*/
        cbxChooseRole.add(adminPanel);
        cbxChooseRole.add(supplierPanel);
    }

    public void populateSupplierCombo() {
        //清空下拉框旧数据，避免重复添加。
        cbxSelectSupplier.removeAllItems();
        
        /*从supplierDirectory.getSupplierList()取出每一个Supplier对象，依次命名为supplier。
          把供应商对象添加到下拉框。*/
        for(Supplier supplier : supplierDirectory.getSupplierList()){
            cmbSelectSupplier.addItem(supplier);
        }
    }
    
    
        //决定供应商下拉框是否显示。
    private void updateSupplierVisibility(){
        //用户还没选择任何角色 或 用户选择的是管理员角色，则不需要去选择供应商。
        if(cbxChooseRole.getSelectedItem() == null || cbxChooseRole.getSelectedItem().getClass() == AdminWorkAreaJPanel.class){
        selectedSupplier = null;//如满足上述任意条件，则清空该值。
        lblSelectSupplier.setVisible(false);//.setVisible(false)就是让控件从界面上隐藏。
        cmbSelectSupplier.setVisible(false);
     }
        //如果用户在Role下拉框选择了Supplier角色，就显示选择供应商的下拉框和它的标签。
        if(cbxChooseRole.getSelectedItem().getClass() == SupplierWorkAreaJPanel.class){
            lblSelectSupplier.setVisible(true);
            cmbSelectSupplier.setVisible(true);
        }
    }
}
