/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author Eve Dou
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Product product;
    public CreateJPanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        fieldDescription = new javax.swing.JTextField();
        lblAvailability = new javax.swing.JLabel();
        fieldAvailability = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        fieldprice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblManuStreet = new javax.swing.JLabel();
        lblManuUnit = new javax.swing.JLabel();
        lblManuCity = new javax.swing.JLabel();
        lblManuZipcode = new javax.swing.JLabel();
        fieldManuStreet = new javax.swing.JTextField();
        fieldManuUnit = new javax.swing.JTextField();
        fieldManuCity = new javax.swing.JTextField();
        fieldManuZipcode = new javax.swing.JTextField();
        lblShippingStreet = new javax.swing.JLabel();
        lblShippingUnit = new javax.swing.JLabel();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipcode = new javax.swing.JLabel();
        fieldShippingStreet = new javax.swing.JTextField();
        fieldShippingUnit = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        fieldShippingZipcode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setText("Create a Product");

        lblName.setText("Name");

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        lblDescription.setText("Description");

        fieldDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescriptionActionPerformed(evt);
            }
        });

        lblAvailability.setText("Availability");

        lblPrice.setText("Price");

        jLabel1.setText("Manufacture Address");

        jLabel2.setText("Shipping Address");

        lblManuStreet.setText("Street Name");

        lblManuUnit.setText("Unit Number");

        lblManuCity.setText("City");

        lblManuZipcode.setText("Zip Code");

        fieldManuCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldManuCityActionPerformed(evt);
            }
        });

        lblShippingStreet.setText("Street Name");

        lblShippingUnit.setText("Unit Number");

        lblShippingCity.setText("City");

        lblShippingZipcode.setText("Zip Code");

        fieldShippingStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingStreetActionPerformed(evt);
            }
        });

        fieldShippingZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldShippingZipcodeActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblManuCity)
                                    .addComponent(lblManuUnit)
                                    .addComponent(lblManuZipcode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldManuUnit)
                                    .addComponent(fieldManuCity)
                                    .addComponent(fieldManuZipcode)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblManuStreet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldManuStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblShippingStreet)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(lblShippingZipcode))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblShippingCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblShippingUnit, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldShippingStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(fieldShippingUnit)
                                    .addComponent(fieldShippingCity)
                                    .addComponent(fieldShippingZipcode)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescription)
                                    .addComponent(lblAvailability)
                                    .addComponent(lblPrice))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldDescription)
                                    .addComponent(fieldAvailability)
                                    .addComponent(fieldprice)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(42, 42, 42)
                                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnSave)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailability)
                    .addComponent(fieldAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(fieldprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManuStreet)
                            .addComponent(fieldManuStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManuUnit)
                            .addComponent(fieldManuUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblManuCity)
                            .addComponent(fieldManuCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblManuZipcode)
                            .addComponent(fieldManuZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShippingStreet)
                            .addComponent(fieldShippingStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShippingUnit)
                            .addComponent(fieldShippingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShippingCity)
                            .addComponent(fieldShippingCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblShippingZipcode)
                            .addComponent(fieldShippingZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescriptionActionPerformed

    private void fieldManuCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldManuCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldManuCityActionPerformed

    private void fieldShippingStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingStreetActionPerformed

    private void fieldShippingZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldShippingZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldShippingZipcodeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String name = fieldName.getText();
        String description = fieldDescription.getText();
        String avail = fieldAvailability.getText();
        String price = fieldprice.getText();
        
        String manuStreet = fieldManuStreet.getText();
        String manuUnit = fieldManuUnit.getText();
        String manuCity = fieldManuCity.getText();
        String manuZipcode = fieldManuZipcode.getText();
        
        String shippingStreet = fieldShippingStreet.getText();
        String shippingUnit = fieldShippingStreet.getText();
        String shippingCity = fieldShippingCity.getText();
        String shippingZipCode = fieldShippingZipcode.getText();
        
        product.setName(name);
        product.setDescription(description);
        product.setAvailNum(avail);
        product.setPrice(price);
        
        product.getManufactureAddress().setStreetName(manuStreet);
        product.getManufactureAddress().setUnitName(manuUnit);
        product.getManufactureAddress().setCity(manuCity);
        product.getManufactureAddress().setZipCode(manuZipcode);
        
        product.getShippingAddress().setStreetName(shippingStreet);
        product.getShippingAddress().setUnitName(shippingUnit);
        product.getShippingAddress().setCity(shippingCity);
        product.getShippingAddress().setZipCode(shippingZipCode);
        
        JOptionPane.showMessageDialog(this,"Successfully Saved!");
        
        fieldName.setText("");
        fieldDescription.setText("");
        fieldAvailability.setText("");
        fieldprice.setText("");
        fieldManuStreet.setText("");
        fieldManuUnit.setText("");
        fieldManuCity.setText("");
        fieldManuZipcode.setText("");
        fieldShippingStreet.setText("");
        fieldShippingUnit.setText("");
        fieldShippingCity.setText("");
        fieldShippingZipcode.setText("");
        
        
                
        
        
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAvailability;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldManuCity;
    private javax.swing.JTextField fieldManuStreet;
    private javax.swing.JTextField fieldManuUnit;
    private javax.swing.JTextField fieldManuZipcode;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreet;
    private javax.swing.JTextField fieldShippingUnit;
    private javax.swing.JTextField fieldShippingZipcode;
    private javax.swing.JTextField fieldprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAvailability;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblManuCity;
    private javax.swing.JLabel lblManuStreet;
    private javax.swing.JLabel lblManuUnit;
    private javax.swing.JLabel lblManuZipcode;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreet;
    private javax.swing.JLabel lblShippingUnit;
    private javax.swing.JLabel lblShippingZipcode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
